version: '3.3'
services:
  postgres:
    container_name: postgres
    image: "postgres:11-alpine"
    restart: always
    ports:
      - "5400:5432"
    volumes: 
      - ./order-app/docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
    environment:
      - POSTGRES_USER=yusuf
      - POSTGRES_PASSWORD=yusuf
      - POSTGRES_DB=storedb 
  mongo:
    container_name: mongo
    image: "mongo"
    ports: 
     - "27021:27017"
  backend:
    container_name: server
    build: ./order-app
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - "mongo" 
  frontend:
      container_name: client
      build: ./order-app-frontend
      restart: always
      ports:
        - "8080:80"
      